config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'posts#index', as: 'home'
get 'about' => 'pages#about', as: 'about'

resources :posts do
resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence:true,
                    length: {minimum:5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "Dhimana", password:"Saurav91#", only: [:destroy]
    def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
end
def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
end
private def comment_params
params.require(:comment).permit(:userName, :body)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 def about
    @title = 'JSMPJ Corporation';
    @page = 'About Us'
    @content = 'This is the about Page'
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   http_basic_authenticate_with name: "Dhimana", password:"Saurav91#", except: [:index, :show]
   def index
    @heading = 'JSMPJ'
    @page='Home Page'
    @content='This is home page'
    @posts=Post.all
 end

 def show
    @post=Post.find(params[:id])
 end

 def new
    @post = Post.new
 end

 def edit
   @post=Post.find(params[:id])
 end

 def update
   @post=Post.find(params[:id])
   if(@post.update(post_params))
      redirect_to @post
      else
          render 'new'
   end
 end

 def create
#    render plain: sparams[:post].inspect
    @post = Post.new(post_params)
    if(@post.save)
    redirect_to @post
    else
        render 'new'
 end

 def destroy
   @post = Post.find(params[:id])
   @post.destroy
   redirect_to posts_path
 end

end
 private def post_params
 params.require(:post).permit(:title, :body)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <p><strong><%= comment.userName %></strong>: <%= comment.body%></p>
    <%= link_to '[X]', [comment.post, comment], 
method: :delete,
data:{confirm: 'Are you sure to delete it?'}
 %>
   </ol>
   </nav>
    <% end %>
<hr>

app/views/comments/_form.html.erb
<h3>Add Comments<h3>
<%= form_for([@post, @post.comments.build])  do |f| %>
    <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
    <% end %>
    <p>
    <%= f.label :userName %><br>
    <%= f.text_field(:userName, {:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to "Home", home_path %></li>   </ul>
     <ul class="nav navbar-nav"> <li class="nav-item"><%= link_to "Create post", new_post_path %>
     </li>
    </ul>
  </div>
</nav>
<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %> </h1>
<h3><%= @page %></h3>
<h6><%= @content%></h6>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
    <% end %>
    <p>
    <%= f.label :title%><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>    

app/views/posts/index.html.erb
<h1><%= @heading%></h1>
<h3><%= @page%></h3>
<p><%= @content%></p>
<h3>Belog post</h3>
<% @posts.each do |post| %>


<div class="card">
  
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>
    <p class="card-text"><%= post.body %></p>
    <%= link_to "Read More", post_path(post), :class => 'btn btn-info' %>
  </div>
</div>
<br>
<% end %>

app/views/posts/new.html.erb
<h1>Add posts for JSMPJ Corporation</h1>
<%= form_for :post, url: posts_path  do |f| %>
    <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
    <% end %>
    <p>
    <%= f.label :title%><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body,{:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>    

app/views/posts/show.html.erb
<h1>JSMPJ Corporation</h1>
<h2><%= @post.title %></h2>
<h2><%= @post.body%></h2>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-primary' %>
<%= link_to "Delete", post_path(@post), 
method: :delete,
data:{confirm: 'Are you sure to delete it?'},
:class => 'btn btn-danger' %>
<hr>
<%= render 'comments/comments' %>
<%= render 'comments/form' %>
  